### ISSUE TITLE
mpv doesn't appear in the Default Programs list on a vanilla Windows 10 1511 install

### ISSUE THREAD

**Issue by rossy** [rossy/mpv-install#6]
Will investigate.

![image](https://cloud.githubusercontent.com/assets/162837/15813116/92a8bc36-2bff-11e6-905b-216ed7f5079b.png)

**Comment by hrxn** [comment]
Can confirm, same here.

I don't know exactly when, but this did work not long ago. So it has to be some recent change made to Windows.

**Comment by DarkstaIkers** [comment]
Yeah, same here too.

**Comment by rossy** [comment]
Ok so hopefully mpv-player/mpv@bf2e2bf fixes this. The next build of mpv should work.

**Comment by rossy** [comment]
FWIW, mpv 0.19.0 is out on https://mpv.srsfckn.biz/, so this should be fixed for real.
