### ISSUE TITLE
Error in command: reg add "" /v "FriendlyTypeName" /d "" /f

### ISSUE THREAD

**Issue by 4trdg** [rossy/mpv-install#7]
Hi,

I get an error when trying to run the batch file in Windows 7 64-bit:

![untitled](https://cloud.githubusercontent.com/assets/20238866/16515364/ba77488e-3fc5-11e6-9997-3df683cfecba.png)

**Comment by rossy** [comment]
I'm not sure what this could be. Can you confirm you're running the script as administrator (or with UAC disabled) and that you downloaded the script from https://github.com/rossy/mpv-install/archive/master.zip (if you download from other parts of the GitHub interface, the file may have the wrong line endings.)

**Comment by rossy** [comment]
I just tested on a vanilla Windows 7 install and I get the same error if I use the script as downloaded from here: https://raw.githubusercontent.com/rossy/mpv-install/master/mpv-install.bat

Instead, it should be downloaded from here: https://github.com/mpv-player/mpv/archive/master.zip

I think this is what happened, so I'm tentatively closing this issue. If this wasn't the problem, please reopen.

**Comment by moopie** [comment]
@rossy just stumbled to this problem myself and can confirm that downloading the zip solved the issue

**Comment by rossy** [comment]
@moopie Yeah, I tend to instinctively use GitHub's raw links too. I should document this.
